deployment:
  tasks:
    - export DEPLOYPATH=/home/clickecom/vitaepro.com.au
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp -R *.html $DEPLOYPATH || true
    - /bin/cp -R *.js $DEPLOYPATH || true
    - /bin/cp -R *.css $DEPLOYPATH || true
